language: cpp
sudo: required
dist: xenial
compiler:
- clang
os:
- linux
- osx
before_install:
install:
- ./install_dep_travis.sh
script:
- ./build_travis.sh
after_success:
branches:
only:
  - develop
notifications:
email: false
template:
    - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"
webhooks:
urls:
on_success: always
on_failure: always
on_start: always
env:
global:
