language: cpp
sudo: required
dist: xenial
compiler:
- clang
os:
- linux
before_install:
install:
- cd ~ && wget https://e.iotee.io/db-18.1.25.tgz
- tar zxf db-18.1.25.tgz
- cd ~/db-18.1.25/build_unix && sudo make instal
- mkdir ~/opt  && cd ~/opt && wget https://e.iotee.io/wasm.tgz
- tar zxf wasm.tgz
- cd ~/opt && wget https://e.iotee.io/boost_1_69_0.tgz 
- tar zxf boost_1_69_0.tgz
script:
- cd contracts/musl/upstream && git checkout eosio
- cd ../../.. && mkdir -p build &&  cd build
- cmake -DWASM_ROOT=~/opt/wasm -DCMAKE_CXX_COMPILER=~/opt/wasm/bin/clang++ -DCMAKE_C_COMPILER=~/opt/wasm/bin/clang -DOPENSSL_ROOT_DIR=/usr/include/openssl -DOPENSSL_INCLUDE_DIR=/usr/include/openssl -DBOOST_ROOT=~/opt/boost -DCMAKE_BUILD_TYPE=Release ..
- make -j2
after_success:
branches:
only:
  - develop
notifications:
email: false
template:
    - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"
webhooks:
urls:
on_success: always
on_failure: always
on_start: always
env:
global:
