language: cpp
sudo: required
dist: xenial
compiler:
- clang
os:
- linux
before_install:
- apt list --installed | grep llvm
- sudo apt-get -y remove libllvm3.8
- sudo apt-get -y remove libllvm6.0
- sudo apt-get -y remove llvm
- apt list --installed | grep llvm
install:
- cd ~ && wget https://e.iotee.io/db-18.1.25.tgz
- tar zxf db-18.1.25.tgz
- cd ~/db-18.1.25/build_unix && sudo make install
- mkdir ~/opt  && cd ~/opt && wget https://e.iotee.io/wasm.tgz
- tar zxf wasm.tgz
- cd ~/opt && wget https://e.iotee.io/boost_1_69_0.tgz 
- tar zxf boost_1_69_0.tgz
script:
- cd $TRAVIS_BUILD_DIR/contracts/musl/upstream && git checkout eosio
- cd $TRAVIS_BUILD_DIR && mkdir -p build && cd build
- export PATH=~/opt/wasm/bin:$PATH
- ../build_linux.sh
after_success:
branches:
only:
  - develop
notifications:
email: false
template:
    - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"
webhooks:
urls:
on_success: always
on_failure: always
on_start: always
env:
global:
